# Generated by Django 3.1.1 on 2021-07-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='bookPrice',
            field=models.IntegerField(default='2000'),
        ),
    ]
