# Generated by Django 3.1.1 on 2021-07-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_propertydetails_bookprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='bookPrice',
            field=models.IntegerField(default='2000.00'),
        ),
    ]
