# Generated by Django 3.1.1 on 2021-07-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propertybuy', '__first__'),
        ('seller', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_detailes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.propertydetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertybuy.userproile')),
            ],
            options={
                'unique_together': {('seller', 'user')},
            },
        ),
    ]
