# Generated by Django 3.1.1 on 2021-07-05 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('propertybuy', '0001_initial'),
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('total_amt', models.DecimalField(decimal_places=3, max_digits=10)),
                ('amt_status', models.IntegerField(default=0)),
                ('order_status', models.IntegerField(default=0)),
                ('placedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertybuy.userproile')),
            ],
        ),
        migrations.CreateModel(
            name='BookProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.book')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.propertydetails')),
            ],
        ),
    ]
